name: Flow Type Checking

on: [push, pull_request]

jobs:
  flow-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14  # Adjust the Node.js version as needed

      - name: Install dependencies
        run: npm install

      - name: Add devDependency on flow-bin
        run: npm install --save-dev flow-bin

      - name: Initialize Flow
        run: npm run flow init

      - name: Run Flow
        run: npm run flow
