name: Test

on:
  push:
    branches:
      - testing

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  unit_test:
    name: Unit Test
    steps:
      - uses: actions/checkout@v3
      - run: test/unit_test.js
