name: UnitTest

on:
  push:
    branches:
      - testing

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  unit_test:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: cp install/package.json package.json
      - run: npm test test/unit_test.js
