name: Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  unit_test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Running Unit Tests for Anonymous Button feature"
      - uses: actions/checkout@v4
      - run: echo "This job's status is ${{ job.status }}"